carts/urls.py
from django.urls import path
from . import views as v

app_name = 'cart'

urlpatterns = [
    path('', v.cart_home, name='home'),
    path('update', v.cart_update, name='update'),
    path('checkout', v.checkout_home, name='checkout'),
    path('checkout/success', v.checkout_done_view, name='checkout-success'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from django.urls import path, include
from accounts.views import LoginView, home_page, RegisterView, about_page, contact_page, guest_register
# from .views import about_page, contact_page
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view


urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', LoginView.as_view(), name='login'),
    path('checkout/address/create', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guest', guest_register, name='guest_register'),

    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),

    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import (
    ProductListView,
    ProductDetailView,
    ProductDetailSlugView,
    ProductFeaturedListView,
    ProductFeaturedDetailView
)

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    # path('featured', ProductFeaturedListView.as_view()),
    # path('<int:pk>', ProductDetailView.as_view()),
    path('<slug>', ProductDetailSlugView.as_view(), name='detail'),
    # path('featured/<int:pk>', ProductFeaturedDetailView.as_view()),
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<!--FontAwesome CSS-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!--<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">-->

<!--Custom CSS-->
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<!--jQuery Confirm-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<!--jQuery Confirm-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>


<!--Django Secure AJAX JS-->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!--eCommerce Custom JS-->
<script src="{% static 'js/ecommerce.js' %}"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'about' as about_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'products:detail' as products_detail_url %}
{% url 'products:list' as products_list_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      {% if brand_name %} {{ brand_name }} {% else %} eCommerce {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == about_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
          <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'products:list'%}">Products</a>
        </li>
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
          <a class="nav-link" href="{{ cart_url }}"> <span class="navbar-cart-count"><i class="fa fa-shopping-cart" aria-hidden="true"></i> <sup>{{ request.session.cart_items }}</sup></span> </a>
        </li>
<!--        <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
        {% if request.user.is_authenticated  %}
          <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
            <a class="nav-link" href="{{logout_url}}">Logout</a>
          </li>
        {% else %}
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link" href="{% url 'login'%}">Login</a>
        </li>
        <li class="nav-item {% if request.path == register_url %}active{% endif %}">
            <a class="nav-link" href="{% url 'register'%}">Register</a>
        </li>
        {% endif %}
      </ul>
<!--      search form-->
      {% include 'search/snippets/search_form.html' %}
    </div>
    </div>
</nav>